FROM docker.io/homebrew/brew:latest

RUN brew install git imagemagick

RUN git clone --depth 1 --branch $(curl -s https://api.github.com/repos/fedoradesign/backgrounds/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")') https://github.com/fedoradesign/backgrounds.git defaults \
&& cd defaults/default \
&& mv *day.jxl light.jxl \
&& mv *night.jxl dark.jxl \
&& magick light.jxl light.png \
&& magick light.jxl -blur 0x25 light-blur.png \
&& magick dark.jxl dark.png \
&& magick dark.jxl -blur 0x25 dark-blur.png
