FROM --platform=$BUILDPLATFORM alpine:latest AS builder
RUN --mount=type=cache,target=/var/cache/apk apk add --no-cache libjxl-tools imagemagick curl jq
WORKDIR /work
# fetch latest tarball and extract
RUN curl -fsSL "https://api.github.com/repos/fedoradesign/backgrounds/releases/latest" \
  | jq -r '.tarball_url' \
  | xargs curl -fsSL \
  | tar -xz --strip-components=1
# normalize filenames and render pngs
RUN light=$(echo default/*day.jxl) \
  && dark=$(echo default/*night.jxl) \
  && djxl $light light.png \
  && djxl $dark dark.png \
  && magick light.png -blur 0x25 light-blur.png \
  && magick dark.png -blur 0x25 dark-blur.png

# export wallpapers
FROM scratch AS export
COPY --from=builder /work/*.png /

# podman buildx build --target export --output type=local,dest=./wallpapers .
